### ISSUE TITLE
Question about use of Implicits

### ISSUE THREAD

**Issue by doshmajhan** [Devolutions/picky-rs#11]
Hey all, I'm currently using the `picky-asn1` library to try and implement [RFC 5652](https://tools.ietf.org/html/rfc5652) and am a bit confused about how Implicits are used here. 

For example, we have the following ASN1 notation:

```
SignerInfo ::= SEQUENCE {
        version CMSVersion,
        sid SignerIdentifier,
        digestAlgorithm DigestAlgorithmIdentifier,
        signedAttrs [0] IMPLICIT SignedAttributes OPTIONAL,
        signatureAlgorithm SignatureAlgorithmIdentifier,
        signature SignatureValue,
        unsignedAttrs [1] IMPLICIT UnsignedAttributes OPTIONAL }

SignedAttributes ::= SET SIZE (1..MAX) OF Attribute

Attribute ::= SEQUENCE {
        attrType OBJECT IDENTIFIER,
        attrValues SET OF AttributeValue }

AttributeValue ::= ANY

```

And I have the corresponding rust code for this:
```
#[derive(Deserialize, Serialize)]
struct Attribute<T> {
    attr_type: ObjectIdentifierAsn1,
    attr_values: Asn1SetOf<T>
}

#[derive(Deserialize, Serialize)]
pub struct SignedAttributes(Asn1SetOf<Attribute<OctetStringAsn1>>);

#[derive(Deserialize, Serialize)]
struct SignerInfo {
    version: u128,
    sid: IssuerAndSerial,
    digest_algorithm: AlgorithmIdentifier,
    signed_attributes: Implicit(ApplicationTag0<SignedAttributes>),
    digest_encryption_algorithm: AlgorithmIdentifier,
    signature: OctetStringAsn1,
}
```

My thought would be that the `Implicit` tag belongs on the `signed_attributes` field in the `SignerInfo` struct. But compilation fails stating that the trait `std::default::Default` is not implemented for `SignedAttributes`. Is that something that I need to implement here or am I using the `Implicit` tag incorrectly?

**Comment by bcortier-devolutions** [comment]
Hi!

Did you resolve your issue?

Indeed the `Default` trait has to be implemented because if the Implicit field isn't provided a default value is implicitly provided (for instance in X.509 certificates version tag is 1 by default).
If the field is optional you have to use `Option` whose default is `None` :slightly_smiling_face:

**Comment by doshmajhan** [comment]
Yes, I was able to resolve it after playing around with it for a while, thank you for the follow up though!

**Comment by doshmajhan** [comment]
Kind of a follow-up question, is it possible to include a field in a struct that doesn't get tagged when serializing? For example, I have a `Vec<u8>` that is already a valid DER encoded structure, but if I pass it into a struct that is being serialized, it will get retagged as an `OctetString` due to its value of `Vec<u8>`. Is there a way to avoid that?

**Comment by bcortier-devolutions** [comment]
I don't think this use-case is properly covered yet. I can add a wrapper type to mark the field as raw user-provided DER such as
```rust
struct Asn1RawDer(pub Vec<u8>)
```
Also as it is a DER-only feature it would be located in `picky-asn1-der` crate and not `picky-asn1`. That is, except if there is another more general use-case?

Either way, I'll make an update this week.

**Comment by doshmajhan** [comment]
That would be perfect! And I agree with you that it should belong in the `picky-asn1-der` crate. Thank you again for all the help.

**Comment by bcortier-devolutions** [comment]
I publish version 0.2.1 with the wrapper struct. You can check [doc](https://docs.rs/picky-asn1-der/0.2.1/picky_asn1_der/struct.Asn1RawDer.html) :slightly_smiling_face:

**Comment by doshmajhan** [comment]
You're doing gods work, thank you!
