### ISSUE TITLE
Release candidate tag got removed

### ISSUE THREAD

**Issue by flavio** [Devolutions/picky-rs#137]
Hello, I noticed that with the release of `picky-7.0.0-rc.2` the previous release candidate tag (`picky-7.0.0-rc.1`) has been removed.

Could you leave these tags around? I would appreciate that because this suddenly broke `sigstore-rs`, which was building from the `rc1` tag. :pray: 

Thanks!

**Comment by CBenoit** [comment]
Oh! Forgive me, the tag is back :slightly_smiling_face:

Tags should not get removed, but since it's also published on `crates.io` I would recommend using that just to be safe: https://crates.io/crates/picky/versions

Have a good day!

**Comment by flavio** [comment]
Ohh, I didn't notice the tag on crates.io; that's because it's a RC and it doesn't (rightfully) show up on the [main page](https://crates.io/crates/picky).

Thanks, I'll just start consuming the code from crates.io :)
