### ISSUE TITLE
Asn1RawDer with Application/Context tags

### ISSUE THREAD

**Issue by doshmajhan** [Devolutions/picky-rs#14]
Something I noticed when using the new Asn1RawDer type _(thank you by the way for adding that)_ is if you wrap it in something like `ApplicationTag0` the Application tag doesn't get included when serializing the data.

For example if you have `ApplicationTag0(Asn1RawDer(to_vec(&data).unwrap()))`  it would be seralized into something like:
```
SEQUENCE
   ... etc
```
instead of 
```
[0]
    SEQUENCE
        ... etc
```

Is this the intended functionality with the `Asn1RawDer` type?

**Comment by bcortier-devolutions** [comment]
Thank you for reporting the issue. I'll have a look this week.

**Comment by bcortier-devolutions** [comment]
Fixed in `picky-asn1-der` v0.2.2
