### ISSUE TITLE
parse CSR DirectoryName,  subject

### ISSUE THREAD

**Issue by greenpdx** [Devolutions/picky-rs#191]
I have created a CSR using pkijs the subject having many fields.
GN = Bob+SN = Test+telephoneNumber = 50655555555+emailAddress = test@eample.com+CN = Test CSR+OU = Dev+O = Example Com+L = Zaragosa+ST = Alajula+C = CR

let bcsr = Csr::from_pem_str(&csrStr).unwrap()
let csrName = bcsr.subject_name();

Here is the first part of the csrName
DirectoryName(Name(Asn1SequenceOf([Asn1SetOf([AttributeTypeAndValue { ty: ObjectIdentifierAsn1(ObjectIdentifier { root: JointIsoItuT, first_node: 5, child_nodes: [4, 6] }), value: CountryName(PrintableString(PrintableStringAsn1(RestrictedString { data: [67, 82], marker: PhantomData }))) }, AttributeTypeAndValue { ty: ObjectIdentifierAsn1(ObjectIdentifier { root: JointIsoItuT, first_node: 5, child_nodes: [4, 8] }), value: StateOrProvinceName(Utf8String("Alajula")) }, .....

So I have a Vec<AttributeTypeAndValue> with a ty: 2.5.4.6 and a value: CR  * Costa Rica not Carriage Return 
as the first entry in Vec

Is there a way to get all the fields in a Vec?

**Comment by CBenoit** [comment]
I see you opened a pull request for that. Thank you!
