### ISSUE TITLE
Requesting publish on Crates.io

### ISSUE THREAD

**Issue by itsbalamurali** [Devolutions/picky-rs#203]
Hey, there team!

Thanks for this great project/library. I would like to use a few pkcs7 features that are not published in crates.io. Currently using rust-OpenSSL at the moment. Any timeline is appreciated.

**Comment by CBenoit** [comment]
Hello @itsbalamurali!

Sorry for the delay! I’ll look into it today

**Comment by CBenoit** [comment]
Hey @itsbalamurali 

There is already a version published on crates.io with pkcs7 available: https://docs.rs/picky/7.0.0-rc.3/src/picky/x509/mod.rs.html#131

You may add
```toml
picky = { version = "7.0.0-rc.3", features = ["pkcs7"] }
```
to your Cargo.toml :slightly_frowning_face: 

Sadly the documentation is not built with the pkcs7 feature enabled so it doesn’t appear in docs.rs, but I’ll look into that!

**Comment by CBenoit** [comment]
Closing as it’s available on crates.io.
