### ISSUE TITLE
picky-signtool: replace `lief-cwal` crate with `object` crate (pure Rust)

### ISSUE THREAD

**Issue by pkking** [Devolutions/picky-rs#213]
Is there a plan to build picky as a pure rust binary/crates as some unsafe code still lives there, e.g. lief-cwal :)

**Comment by CBenoit** [comment]
lief-cwal is a dependency of [picky-signtool](https://github.com/Devolutions/picky-rs/tree/master/picky-signtool), other crates do not depend on it and are pure Rust as far as I know (we use RustCrypto instead of ring for that reason).
There is no plan to rewrite the lief project in Rust just for picky-signtool.

**Comment by RRRadicalEdward** [comment]
It would be possible if there is a Rust library for decoding, modifying, and encoding PE files.
The last time, I checked there wasn't any.

**Comment by CBenoit** [comment]
> It would be possible if there is a Rust library for decoding, modifying, and encoding PE files. The last time, I checked there wasn't any.

I wonder if [goblin](https://crates.io/crates/goblin) or [object](https://crates.io/crates/object) could do the job?

**Comment by RRRadicalEdward** [comment]
I just checked [object::write::pe::Writer](https://docs.rs/object/0.31.0/object/write/pe/struct.Writer.html) and it should do the job

**Comment by CBenoit** [comment]
> I just checked [object::write::pe::Writer](https://docs.rs/object/0.31.0/object/write/pe/struct.Writer.html) and it should do the job

Great!

I renamed the issue to reflect how things could be actioned.

Note that picky-signtool is not a priority anymore for us (Devolutions), but pull requests from the community are welcomed :slightly_smiling_face:
