### ISSUE TITLE
please include license files in published crates

### ISSUE THREAD

**Issue by decathorpe** [Devolutions/picky-rs#230]
This is a followup for https://github.com/Devolutions/picky-rs/issues/56. It appears that there was a misunderstanding about some things, so I will try to clarify:

Both the MIT and the Apache-2.0 license terms contain a requirement that redistributed sources (i.e. via crates.io, or via Linux distribution packages) contain a copy of the original license text.

So for our purposes (RPM packages for Fedora Linux), it is indeed a requirement to include the original license texts, and the same could be argued for crates distributed via crates.io (it is not a *general* requirement, but it *is* a requirement of the Apache-2.0 and MIT licenses).

I can submit a pull request to add symlinks so that cargo publish includes license files in published crates (full copies of the files are *not* required, unless you're publishing from an operating system that does not support symlinks properly, i.e. Windows).

**Comment by CBenoit** [comment]
Sounds fair to me. As you said, it’s likely we misunderstood something back then and I see no point in making packagers' lives harder. I welcome a pull request to add the symlinks. You’ll also need to specify the files in [the `include` field of each `Cargo.toml`](https://github.com/Devolutions/picky-rs/blob/8415e7eaa9ed27e57118c60e18e379567ceffd53/picky/Cargo.toml#L21) (we are following [The Lean Crate Initiative](https://github.com/the-lean-crate/criner) and are making sure we only include the the bare essentials in our packages). Thank you!
