### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by dmulder** [Devolutions/picky-rs#270]
Why is nothing documented here?

**Comment by dmulder** [comment]
I finally figured out how it works by reading through your test cases, and it works beautifully! This project seriously needs to be documented though.

**Comment by CBenoit** [comment]
Hi! I'm glad to hear that you were able to make it work! We are aware that the documentation is lacking, but unfortunately, we don’t have enough bandwidth to document everything right now. Ideally, documentation should be written when the code is written. Some modules (https://docs.rs/picky/latest/picky/http/index.html) were documented in this way, but sadly, things are not always that simple. However, if you are willing to contribute documentation, especially regarding what you had to research for your use case, we would gladly start improving things by merging it! Thank you!

**Comment by dmulder** [comment]
Take a look at #274. That little tidbit would have been helpful when I was evaluating crates on crates.io.

**Comment by CBenoit** [comment]
Thank you a lot for that!
