### ISSUE TITLE
Parsing email attribute in certificate Subject

### ISSUE THREAD

**Issue by Albibek** [Devolutions/picky-rs#43]
Hi. 

I was trying to use the picky-asn1-x509 library for parsing a certificate of one of internal CAs used in company I work for. Unfortunately that CA was created using openssl and contains and email (`IA5String`) field in subject and I've got [an error](https://github.com/Devolutions/picky-rs/blob/06ae4025f4f7d99e42201cd27c655fbf59c233b8/picky-asn1-x509/src/attribute_type_and_value.rs#L192) when trying to parse it. 

I did a small chek on my ArchLinux system and found that two long-living "official" CAs also contain such field:

```bash
$ for i in $(find /etc/ssl/certs/ -type f,l | grep -v java/cacerts); do openssl x509 -subject -noout <$i | grep @; done
subject=C = EE, O = AS Sertifitseerimiskeskus, CN = EE Certification Centre Root CA, emailAddress = pki@sk.ee
subject=C = EE, O = AS Sertifitseerimiskeskus, CN = EE Certification Centre Root CA, emailAddress = pki@sk.ee
subject=C = HU, L = Budapest, O = Microsec Ltd., CN = Microsec e-Szigno Root CA 2009, emailAddress = info@e-szigno.hu
subject=C = HU, L = Budapest, O = Microsec Ltd., CN = Microsec e-Szigno Root CA 2009, emailAddress = info@e-szigno.hu
subject=C = HU, L = Budapest, O = Microsec Ltd., CN = Microsec e-Szigno Root CA 2009, emailAddress = info@e-szigno.hu
subject=C = EE, O = AS Sertifitseerimiskeskus, CN = EE Certification Centre Root CA, emailAddress = pki@sk.ee
```

I've thought that some library users may come to a similar problem, for example if they would want to parse all trusted CAs for some reason or have a same problem with their local CAs. 

Also I did the initial approach on implementing that [here](https://github.com/Devolutions/picky-rs/commit/d729644197bd43f601481d3359def659f1058e54) and it "works on my machine".

Would you accept this as a PR? Since it is a rarely needed feature that breaks an actual RFC, we could make it a compilation feature to avoid breaking. I can also write unit tests of course.

**Comment by awakecoding** [comment]
Sure, we'd be glad to accept a PR even if it is a rarely used feature. @bcortier-devolutions should be able to tell if it would impact us much but I don't think so. Just add the required code you need and we'll review it for proper inclusion.

**Comment by Albibek** [comment]
Can we please discuss https://github.com/Devolutions/picky-rs/issues/44 before? I could provide fixes for both in the same PR.

**Comment by bcortier-devolutions** [comment]
It indeed is deprecated and that's why I didn't put work into it but if you intend to make it works I have no objection, it can't hurt!
There is an "mkcert all stars" test that is explicitly not failing on them here: https://github.com/Devolutions/picky-rs/blob/master/picky/tests/mkcert_all_stars.rs#L59
You may remove this condition in addition to your unit test.
I'll have a look at #44 now.
