### ISSUE TITLE
picky: Typo in CertificateBuilder API

### ISSUE THREAD

**Issue by orndorffgrant** [Devolutions/picky-rs#64]
I think `valididy` is supposed to be `validity` here: https://github.com/Devolutions/picky-rs/blob/master/picky/src/x509/certificate.rs#L604

6.0 might be a good chance to change this since correcting the typo will break backwards compatibility.

Thanks for the library! I'm hoping to use it to replace openssl in my small side project, [devca](https://github.com/orndorffgrant/devca).

**Comment by bcortier-devolutions** [comment]
Woops I overlooked this one! Thank you for reporting.
I just pushed a commit, this will be fixed in next release.

> Thanks for the library! I'm hoping to use it to replace openssl in my small side project, [devca](https://github.com/orndorffgrant/devca).

This is nice to hear! Your requirements are similar to ours. Don't hesitate to reach out if you come across anything strange. PR are welcome too :smile:
