### ISSUE TITLE
Negative serial numbers not accepted by RusTLS

### ISSUE THREAD

**Issue by shutton** [Devolutions/picky-rs#68]
picky's certificate builder provides only random serial numbers, with no [obvious] way to override them.  Unfortunately, the generator can produce negative values, which causes tokio-rustls to fail to connect to a server using one of these with "invalid certificate: BadDER".  The issue appears to be in `generate_serial_number()`, which can produce a number that can go negative when stored in a `IntegerAsn1`(a signed type):

```
fn generate_serial_number() -> Vec<u8> {
    let x = rand::random::<u32>();
    let b1 = ((x >> 24) & 0xff) as u8;
    let b2 = ((x >> 16) & 0xff) as u8;
    let b3 = ((x >> 8) & 0xff) as u8;
    let b4 = (x & 0xff) as u8;
    vec![b1, b2, b3, b4]
}
```

I think the quick fix is probably just to mask off `b1` with `0x7f`.

**Comment by bcortier-devolutions** [comment]
Hi!
Thank you for the report :slightly_smiling_face: 
You are perfectly right, RFC is clear about this
> The serial number MUST be a positive integer assigned by the CA to each certificate.
I fixed by calling `IntegerAsn1::from_bytes_be_unsigned` so that the IntegerAsn1 can never be negative. I'll publish a bugfix picky  release asap.

**Comment by bcortier-devolutions** [comment]
I'll also add a way to override the serial number.

**Comment by bcortier-devolutions** [comment]
New versions are published, you can have a look at [changelog](https://github.com/Devolutions/picky-rs/blob/master/picky/CHANGELOG.md#610-2020-10-21).
Thank you again for reporting :slightly_smiling_face:
