### ISSUE TITLE
How to create a `serverAuth` x509 extension

### ISSUE THREAD

**Issue by drahnr** [Devolutions/picky-rs#70]
Thanks for creating this awesome crate!

I am currently replacing some openssl based code with pure rust, one of the pitfalls here is that currently a key usage of `serverAuth` is used, which I can't seem to replicate.

Help would be much appreciated!

```
        let extended = {
            let mut key_usage = KeyUsage::new(5);
            key_usage.set_digital_signature(true);
            key_usage.set_content_commitment(true);
            key_usage.set_key_encipherment(true);
            key_usage.set_key_agreement(true);
            key_usage.set_data_encipherment(true);
            

            ExtendedKeyUsage::new(vec![
                Extension::new_basic_constraints(None, None).into_non_critical(),
                Extension::new_key_usage(key_usage).into_non_critical(),
                // how to add  `serverAuth` to this?
            ])
        };
```

**Comment by drahnr** [comment]
Solution:

```rust
let extended = ExtendedKeyUsage::new(vec![kp_server_auth()]);
```

**Comment by bcortier-devolutions** [comment]
Hi!
Happy you find this crate useful. :laughing: 

> Solution:
> 
> ```rust
> let extended = ExtendedKeyUsage::new(vec![let extended = ExtendedKeyUsage::new(vec![picky::oids::kp_server_auth()]);]);
> ```

Glad to hear you found the solution!
I'm not sure about the snippet though, maybe a failed copy pasting?

When building an extension manually:
```rust
let eku = ExtendedKeyUsage::new(vec![picky::oids::kp_server_auth()]);
let extension = Extension::new_extended_key_usage(eku);
```

When building a certificate:
```rust
let eku = ExtendedKeyUsage::new(vec![picky::oids::kp_server_auth()]);
let cert = CertificateBuilder::new()
                      .extended_key_usage(eku)
                      …
                      .build()?;
```

**Comment by drahnr** [comment]
Mea culpa, yes, that copy paste did not go well. I did what you outlined. :+1:
