### ISSUE TITLE
Support custom oid in certificate deserialization

### ISSUE THREAD

**Issue by gaetanww** [Devolutions/picky-rs#76]
When running 
```rust
picky::x509::certificate::Cert::from_der(cert_der).unwrap();
```

I get the error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Asn1Deserialization { element: "certificate", source: Message("invalid value: [AttributeTypeAndValue] unsupported type (unknown oid), expected a supported type") }'
```
Some subjectAltNames in the `cert_der` contain custom oid. Is it possible to parse a certificate with custom oids?

**Comment by bcortier-devolutions** [comment]
You're right, this is not yet supported, I'll find a way to make this possible!

**Comment by bcortier-devolutions** [comment]
@gaetanww I just pushed a commit [953a7e2d05baa8de10] with this ability. Can you confirm it does what you expect before?

**Comment by gaetanww** [comment]
Yes, it's working. Thank you very much!
