### ISSUE TITLE
Question on ECParameters

### ISSUE THREAD

**Issue by ionut-arm** [Devolutions/picky-rs#84]
Heya! I had a question about a type that you have implemented in `picky-asn1-x509`, [`ECParameters`](https://docs.rs/picky-asn1-x509/0.5.0/picky_asn1_x509/algorithm_identifier/enum.ECParameters.html), which I assume is implemented as per [RFC 5480](https://datatracker.ietf.org/doc/html/rfc5480#section-2.1.1). I noticed that in the RFC, both `implicitCurve` and `specifiedCurve` are marked as MUST NOT be used, however your implementation does still allow `implicitCurve`. Is this on purpose?

It's somewhat relevant to me because I'm in the process of implementing `ECPrivateKey` to go along with `RSAPrivateKey`, as we need it for `cryptoki`/Parsec :)

**Comment by CBenoit** [comment]
Hi!
At that time I was thinking about making it as complete as possible, but it should probably be removed since we only ever do PKIX :thinking: 
Would it be simpler for you to just disallow `implicitCurve` by removing it from the enum?

**Comment by CBenoit** [comment]
> That would be simple, but it's a breaking change, not necessarily nice to do. I could mark it as deprecated?

Sounds good to me!

**Comment by CBenoit** [comment]
Hi @ionut-arm 
Since I had a breaking change in `picky-asn1-x509` with #83 , I went ahead and removed it in the next "breaking" release (see #85).
I'll close the issue, but feel free to re-open if necessary :slightly_smiling_face:
