### ISSUE TITLE
ApplicationTagN bits are incorrect

### ISSUE THREAD

**Issue by Albibek** [Devolutions/picky-rs#91]
Hi.

I think I've found a bug in ASN.1 implementation for the application tag. 
The standard requires that tag class must be specified in bits 7 and 8 while bit 6 is reserved for constructed/primitive definition.

Here are the links at the simplified explanations:
http://luca.ntop.org/Teaching/Appunti/asn1.html
https://letsencrypt.org/docs/a-warm-welcome-to-asn1-and-der/

The actual code defines application tag bits as [0xA0](https://github.com/Devolutions/picky-rs/blob/704dc1439dfcc5209fe2eda498ea6dedd06532b9/picky-asn1/src/tag.rs#L61) which is 0b10100000 binary and represents a context-specific tag with the constructed bit set. I believe it should be 0x40 (0b01000000) instead. 

It definitely affects tag class matching because of overlapping intervals also making it match order dependent, and this is how I found it. It is also most probably the reason of using multiple tag class confusions for tagged structures like [here](https://github.com/Devolutions/picky-rs/blob/704dc1439dfcc5209fe2eda498ea6dedd06532b9/picky-asn1-x509/src/name.rs#L265), because the whole x509 seems to be using only context specific tags.

In addition, I see some small edge case problem for code doing an OR operation in `Tag::application` and `Tag::context_specific`. For example, passing 254 into one of these constructors will not make a tag class to be correctly set to Application/Context specific leaving it Private instead. To avoid such situation, the higher bits should be cleared first (using 0x3F = 0b00111111) to guarantee the class, or, some numbers should probably not be accepted at all.
```
    #[inline]
    pub const fn application(number: u8) -> Self {
        Tag(number & 0x3f | 0x40)
    }
    
    #[inline]
    pub const fn context_specific(number: u8) -> Self {
        Tag(number & 0x3f | 0x80)
    }

```

Along with fixing I want to propose changing `Tag::is_application` and `Tag::is_context_specific` methods to bit-based comparisons as well, so they are more semantically accurate and possibly a small bit more performant due to less branching.
```
     #[inline]
    pub const fn is_application(self) -> bool {
      self.0 & 0xC0 == 0x40
    }

    #[inline]
    pub const fn is_context_specific(self) -> bool {
         self.0 & 0xC0 == 0x80
    }
```

**Comment by CBenoit** [comment]
Hi @Albibek, thank you for opening the issue!
You are right, I originally made this mistake back when implementing ASN.1 DER in 2019 and realized my misunderstanding when it was too late. I want to go back and fix that some day, but it’s a lot of work that is currently not in my team backlog. Fortunately our x509 implementation is working properly despite the messy ASN.1 internals while it’s not fun to extend on top of it. At some point we’ll want to support BER and I was thinking fixing all this at this moment. My thinking was to maybe use [der-parser](https://lib.rs/crates/der-parser) crate, that is supporting both DER and BER, to build a better serde serializer / deserializer. This would save us from the maintenance cost of our homemade DER parser-encoder code.

**Comment by awakecoding** [comment]
Just to clarify on the possible need for BER: it's used in LDAP and RDP, two protocols we use currently with separate ASN.1 implementations. It's not a hard requirement but it would be great to eventually support BER for that reason.

**Comment by CBenoit** [comment]
> Actually, I did some more thinking after writing this issue and realized, that this problem could be reduced to just the type semantics. Since application tags are not in use in X.509 at all, it would be enough to find-replace ApplicationTagN to something like ContextTagConstructedN, and ContextTagN to something like ContextTagPrimitiveN which seems trivial. Comparison functions still need to be fixed to compare exactly 3 bits, but it is also trivial because `is_application` is not currently used in picky-* crates.

You’re right, I’ll just do that (or accept a PR) and call this issue closed. Other internals improvements and refactors will wait until we need BER (it’ll require changes anyway).

> Also, I did a quick look around and found some more crates supporting DER and BER at the same time, so probably der-parser is not the only solution. For example, [asn1-rs](https://docs.rs/asn1-rs) is said to be the rewritten der-parser, but better and without a note about encoding support being experimental and unstable. I really liked the type system there, especially the TaggedValue wrapper for supporting all kinds of tags through type parameters.

Indeed, looks modern! Thank you for the pointer. I intend to take a deeper look into alternatives when appropriate :slightly_smiling_face:

**Comment by CBenoit** [comment]
I think this is addressed by https://github.com/Devolutions/picky-rs/pull/92 for now :slightly_smiling_face:
