### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by Coding-Badly** [Devolutions/picky-rs#97]
Tagging releases (e.g. `v0.2.5`) makes it significantly easier to review when considering an update.

**Comment by CBenoit** [comment]
Good idea! I shared a few tags for the most recent versions, so you should be able to compare changes between versions of a specific crate like:

```
$ git diff picky-asn1-x509-0.6.0 picky-asn1-x509-0.6.1 picky-asn1-x509/
```
